- oldlog.go
See https://github.com/ipfs/go-ipfs/issues/2434 . go-log needs to expose the list of current subsystems...
> Lay groundwork for "ipfs log ls" command

- .gx/lastpubver
- package.json
- writer.go
Due to race of condition nextCh can be already null when we try to close it
Resolves https://github.com/ipfs/go-ipfs/issues/2732
> Prevent race of contidion from panic

- .gx/lastpubver
- log.go
- package.json
opentracing-go is targeting support for go1.6 becasue of that we must
use a forked version that uses the latest context package
> Use forked opentracing-go

- package.json
The previous commit switched to a forked opentracing build but the forked version still had imports pointing to the original version.
This commit updates the forked version of opentracing-go to one with fixed imports.
> update opentracing-go to fix imports

- log.go
Allows for cleaner code when creating event logs, e.g.
```go
func (s *Session) GetBlock(ctx context.Context, c *cid.Cid) (blk blocks.Block, err error) {
eip := log.EventBegin(ctx, "Session.GetBlock", c)
defer func() {
if err != nil {
eip.SetError(err)
}
eip.Done()
}()
...
}
```
can be reduced to:
```go
func (s *Session) GetBlock(ctx context.Context, c *cid.Cid) (blk blocks.Block, err error) {
eip := log.EventBegin(ctx, "Session.GetBlock", c)
defer func() {
eip.DoneWithErr(err)
}()
...
}
```
> Add DoneWithErr Method

- oldlog.go
This was messing with the line numbers. It was reported and fixed in #33 but that PR isn't formatted.
closes #33
(all credit goes to @jiangsong)
> remove unnecessary ExtraCalldepth

- .gx/lastpubver
- package.json
This updates go-logging to latest github.com/whyrusleeping/go-logging master, which has a fix for a race in `SetLevel()` which I am hitting when running with `-race`.
Upgraded package.json to latest format too.
> gx publish 1.5.6

- log.go
- tracer/recorder.go
1. Pretty format the JSON.
2. Manually convert tag values. According to the opentracing spec, these are only supposed to be strings, ints, and booleans. We were using the standard MarshalJSON interface which was trying to marshal our peer IDs as raw byte strings.
> make logging prettier

- oldlog.go
- Add support for logging to a file  (fixes #22)  via env var: `GOLOG_FILE`
- Add support for logging to syslog via env var: `GOLOG_SYSLOG_ENABLE`
> add env for logging to file and syslog

- oldlog.go
- fork of op/go-logging doesn't have latest code for windows syslogger
fallback
Reason: https://github.com/ipfs/go-log/commit/29c2a5b469efcb231777fcdab5f90d98a4935f12#commitcomment-30495666
Thank you @DanielSel
> remove syslogger

- log.go
- tracer/recorder.go
So, it turns out js-ipfs-api is relying on the fact that go-ipfs spits out ndjson event logs. Furthermore, it turns out that ndjson is just generally easier to parse. Therefore, while pretty logs are pretty, I think it's best to leave this up to the client.
> uglify the (event) logs

- log.go
This is first set toward migrating this pacakage away from event logging and
toward Zap.
The aim is for this pacakge to be a manager for Zap loggers.
> Deprecate EventLogging and Warning* functions

- go.mod
- oldlog.go
This keeps the two full APIs, old and new, intact to make upgrading easier and less confusing.
> add IPFS_* env vars back for transitionary release of go-log

- log.go
Remove `Warningf` method from `StandardLogger` interface to fix error:
`# ***/vendor/github.com/libp2p/go-reuseport/singlepoll
vendor/github.com/libp2p/go-reuseport/singlepoll/linux.go:22:2: cannot use log.Logger("reuseport-poll") (type *log.ZapEventLogger) as type log.EventLogger in assignment:
*log.ZapEventLogger does not implement log.EventLogger (missing Warningf method)`
This error shows up in `v2.0.1` after https://github.com/ipfs/go-log/commit/eede8da5989fa4a4e2408ca2070bb12529954db0 has been merged.
> Remove Warningf method signature from StandardLogger

- path_other.go
- path_windows.go
- setup.go
Fixes #73 by normalizing paths to UNC on windows. This is _slightly_ less hacky than registering a new schema.
The underlying issue was twofold:
1. When specifying a windows file URL as `file://c:/foo/bar`, go barfs because `:` can't be in a domain name.
2. When specifying a windows file URL as `file:///c:/foo/bar`, we'd end up trying to open `/c:/foo/bar` which is actually `CURRENT_DRIVE:/c:/foo/bar`.
> fix: normalize paths on windows

- log.go
Some logger interface requires Warning/Warningf, e.g. badgerDB. So without these two func, go-log cannot be injected into their module.
And deprecated identifier can warn the developers.
> Add avaliable but "Deprecated"-tagged  Warning/Warningf func for compatibility

- log.go
This fixes the caller location.
> fix: skip an additional caller in Warning(f)

- pipe.go
- setup.go
Adds one package level function NewPipeReader which returns a reader
that can be used to listen into the logging output.
Fixes https://github.com/ipfs/go-log/issues/66 and allows go-filecoin
to implement go-filecoin log tail using v2 of go-log
I tried various ways to extend writers/cores in Zap but this seemed to be the best approach that limited new API surface and didn't expose Zap internals.
Happy to be guided on the naming. I chose `Pipe` since that's how it's implemented but an alternative could be `Tee` since it's basically a Tee on the stderr log.
For reference, with this change the go-filecoin log tail function becomes:
```Go
Run: func(req *cmds.Request, re cmds.ResponseEmitter, env cmds.Environment) error {
r := logging.NewPipeReader()
go func() {
defer r.Close() // nolint: …
```
> Support in-memory pipes to read from log

- core.go
- core_test.go
- go.mod
- go.sum
- pipe.go
- pipe_test.go
- setup.go
- setup_test.go
Another take on https://github.com/ipfs/go-log/issues/66
This change introduces a multicore implementation that allows
additonal zap cores to be added at runtime. Each core can be
configured with distinct encoders and writers which makes
it possible to tail the logs in a program using a different
log format (e.g. program may log in json but interactive
tailing can be in plaintext). This comes at the cost of an
additional mutex that must be taken on each write since the
destination of the write is mutable.
It reworks (and simplifies) the pipe reader implementation
added in https://github.com/ipfs/go-log/pull/87 and adds a
new function NewPipeReaderFormat which creates a pipe reader
using a different output format.
This change also allows us to reconfigure logging after it has been …
> Use multiple cores in logger

- log_level_test.go
- pipe.go
- setup.go
Currently, we filter messages at two layers:
1. At individual subsystem loggers.
2. At the final logging core.
However, the final log level was set to ERROR. That meant that reducing the level on subsystem loggers didn't actually do anything. This meant `SetLogLevel` didn't work. This change sets the default log level for pipe readers and the default logging core to DEBUG.
This change also changes the default pipe reader format to JSON to avoid taking a lock. IMO, this should be less surprising regardless as it's more predictable.
I'm not entirely happy about how we're handing log levels but this should be good enough for now. Ideally, we'd have https://github.com/ipfs/go-log/issues/92.
> Fix log level handling

- setup.go
- setup_test.go
This PR introduces a new environment variable that allows a user to enable several log outputs for a logger. The env var is `GOLOG_OUTPUT` and takes a string of outputs concatenated by `+` similar to how the `StandardOutput` directive works in systems. An example value would be `file+stderr` which if `GOLOG_FILE` was set, would log to both the file and stderr.
> enable configuring several log outputs

- setup.go
This may be very useful to pass the logs to some external services like graylog alongside with the stdout/file
Scheme handlers can be registered via `zap.RegisterSink`
> Add an option to pass URL to zap

- setup.go
- setup_test.go
> feat: add ability to specify labels for all loggers

- setup.go
- setup_test.go
Ex:
GOLOG_LOG_LEVEL=error,foo=info,bar=debug
This will set the default log-level to error, foo's log-level o info, and bar's log-level to debug.
fixes #100
> per-subsystem log-levels

- setup.go
- setup_test.go
This PR adds the ability to replace the zap core with a custom one. It should solve the issue: https://github.com/ipfs/go-log/issues/102. 
I explained my reasoning for adding the `SetPrimaryCore` function in this comment: https://github.com/ipfs/go-log/issues/102#issuecomment-850930348.
> feat: add ability to use custom zap core

- go.mod
- go.sum
- setup.go
This is arguably a breaking change, but there really is no legitimate case
for output like this: https://circleci.com/gh/filecoin-project/lotus/189136
The change as implemented respects any explicit setting the user might have
provided, and also keeps coloration in the URL case, in order to minimize
the potential fallout
> Stop defaulting to color output on non-TTY

- setup.go
> In addition to StdOut/Err check the outfile for TTYness

- core.go
- setup_test.go
Calling `SetPrimaryCore` after being configured with a [`zapcore.Tee`](https://pkg.go.dev/go.uber.org/zap/zapcore#NewTee) causes a `panic: runtime error: comparing uncomparable type zapcore.multiCore`
```console
$ go test -v ./... -count 1 -run TestTeeCore
=== RUN   TestTeeCore
failed to IncreaseLevel: invalid increase level, as level "fatal" is allowed by increased level, but not by existing core
--- FAIL: TestTeeCore (0.00s)
panic: runtime error: comparing uncomparable type zapcore.multiCore [recovered]
panic: runtime error: comparing uncomparable type zapcore.multiCore
goroutine 19 [running]:
testing.tRunner.func1.2(0x612ea0, 0xc000099060)
/nix/store/mjpyjqs53d77c691c46kdd97a4094pjm-go-1.16.7/share/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000082900) …
```
> fix: cannot call SetPrimaryCore after using a Tee logger

- go.mod
- go.sum
go-log causes a crash when run on OSX with Go 1.17 and using go-watchdog.
Updating to go-isatty apparently fixes this crash: https://github.com/mattn/go-isatty/pull/66.
> update mattn/go-isatty to v0.0.14

- setup.go
This ended up being a totally microscopic change, but it'll be extremely useful to library users. It is non-breaking change.
This saves the config into a private global variable upon applying it. You can call `GetConfig()` to read a _copy_ of the config, and then it can be modified and re-applied using `SetupLogging()`.
More info at #122. This solution is probably nicer than exposing `configFromEnv()`, because it reflects the _actual_ current state of the logger, which could potentially change before `configFromEnv()` is next called.
> Config inspection

- setup.go
- setup_test.go
When stderr and/or stdout options are configured or specified by the `GOLOG_OUTPUT` environ variable, log only to the output(s) specified.
Replaces #135
Closes #136
> feat: only log to stderr or to stdout or both if configured
